# Site settings
contact: george.lele.sun@gmail.com
company_name: Sun Websites
company_website: https://www.sunwebsites.org
personal_website: http://www.mrsunny.tech
template_readme: https://github.com/mrsunny0/template-gh-pages/blob/gh-pages/README.md
template_generator: https://github.com/mrsunny0/generator-gls-website

# Front page settings
author: George L. Sun
title: mrsunny PhD
header: George Sun's PhD
description: Engineering yeast for heavy metal waste remediation
gh_page: https://mrsunny0.github.io/website-phd-thesis/
background: 
  video: assets/vid/pouring_beer.mp4
  image: assets/img/1000.png 
  color: #1a222c 

# Google-analytics
google-analytics:
  id: "UA-161447266-5"

exclude: ['package.json', 'src' , 'node_modules']